version: "3.9"

services:
  # ---------------------------------------------------
  # MongoDB
  # ---------------------------------------------------
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # ---------------------------------------------------
  # Neo4j
  # ---------------------------------------------------
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/admin@1234
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  # ---------------------------------------------------
  # ETL APPLICATION (RUNS ONCE)
  # ---------------------------------------------------
  pipeline:
    build: ./pipeline
    container_name: ai-mp-personliz-pipeline
    depends_on:
      mongodb:
        condition: service_started
      neo4j:
        condition: service_started
    volumes:
      - ./pipeline:/pipeline
      - ./secrets/sa-key.json:/secrets/sa-key.json:ro
      - milvus_data:/data
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa-key.json
    restart: "no"

  # ---------------------------------------------------
  # FASTAPI QUERY SERVICE (STARTS AFTER ETL)
  # ---------------------------------------------------
  api:
    build: ./api
    container_name: ai-mp-personliz-api
    ports:
      - "8000:8000"
    depends_on:
      etl-app:
        condition: service_completed_successfully
    environment:
      # Neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: admin@1234

      # Milvus Lite
      MILVUS_DB_PATH: /data/milvus_lite.db

      # BigQuery
      BQ_PROJECT: dataservices-dev-stage
      BQ_DATASET: mark_persoliz
      BQ_TABLE: user_data

      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa-key.json
    volumes:
      - milvus_data:/data
      - ./secrets/sa-key.json:/secrets/sa-key.json:ro
    restart: unless-stopped

# ---------------------------------------------------
# Volumes
# ---------------------------------------------------
volumes:
  mongo_data:
  neo4j_data:
  milvus_data:
