INPUT_BUCKET : "ai-marktech-perslz"
FILE_PREFIX : "user_data"
PROJECT_ID : "dataservices-dev-stage"
DATASET_ID: "mark_persoliz"
STG_TABLE_ID: "user_data_stg"
TABLE_ID: "user_data"
FILE_NAME: "ai_marketing_personlization_"
NEO4J_USER: "neo4j"
NEO4J_PASSWORD: "admin@1234"